### ISSUE TITLE
Enhancement Request: Send Along Environment Name as Query Parameter

### ISSUE THREAD

**Issue by denmitchell** [Tricklebyte/ConfigCore#2]
Perhaps it is good practice to always stand up a separate Configuration API server instance in each environment.  That said, I can imagine some scenarios when developers might want to reuse a single Configuration API server to serve multiple environments (e.g., multiple test environments).  

I am requesting that you consider adding an "envName" query parameter to your HTTP Requests that returns the configurations.  envName would simply contain the environment name of the client application (which would typically be the same as the environment name of the Configuration API server).  You wouldn't need another parameter to AddApiSource -- just use ```Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT")``` to retrieve the envName and send it along with the request.

This enhancement wouldn't require any additional handling for your ApiSource/ApiProvider, and it wouldn't break any code for developers who are implementing their own Configuration API servers right now.  It would give implementers the ability to use a single Configuration API server for multiple client environments, when they might want this.

As a side note, if you decide to add envName as a query parameter, then you may want to make appId a query parameter, also.  I wouldn't mind if this broke my code.  It is a simple fix.

**Comment by Tricklebyte** [comment]
Added in Version 3.0
Multiple Route and Query String parameters are now supported that can be configured to filter the results on any number of columns.
